use [F:\GIT\LEARN_ENGLISH\LEARN_ENGLISH\LEARNENGLISHDB.MDF];

UPDATE Step1

SET [Topic] ='COLORS'
WHERE IdWord BETWEEN 1 AND 9

UPDATE Step1
SET[Topic] = 'FAMILY'
WHERE IdWord BETWEEN 10 AND 18
UPDATE Step1
SET[Topic] = 'I LOVE ANIMALS'
WHERE IdWord BETWEEN 19 AND 27
UPDATE Step1
SET[Topic] = 'I CAN'
WHERE IdWord BETWEEN 28 AND 36
UPDATE Step1
SET[Topic] = 'MY TOYS'
WHERE IdWord BETWEEN 37 AND 45
UPDATE Step1
SET[Topic] = 'MY BODY'
WHERE IdWord BETWEEN 46 AND 54
UPDATE Step1
SET[Topic] = 'YUMMY! PART-1'
WHERE IdWord BETWEEN 55 AND 63
UPDATE Step1
SET[Topic] = 'YUMMY! PART-2'
WHERE IdWord BETWEEN 64 AND 72
UPDATE Step1
SET[Topic] = 'MY HOME'
WHERE IdWord BETWEEN 73 AND 81
UPDATE Step1
SET[Topic] = 'I AM PUPIL'
WHERE IdWord BETWEEN 82 AND 90